version: '3.7'

services:

  covid-apps:
    container_name: covid_apps
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    # fix the exit code 0
    stdin_open: true
    tty: true
